;; src/core/opengl-constants.lisp

(in-package :cl-aliengine)

(defconstant +color-buffer-bit+    #x00004000)
(defconstant +triangles+           #x0004)
(defconstant +float-gl+            #x1406)
(defconstant +array-buffer+        #x8892)
(defconstant +dynamic-draw+        #x88E8)
(defconstant +blend+               #x0BE2)
(defconstant +src-alpha+           #x0302)
(defconstant +one-minus-src-alpha+ #x0303)
(defconstant +texture-2d+          #x0DE1)
(defconstant +rgba+                #x1908)
(defconstant +unsigned-byte-gl+    #x1401)
(defconstant +texture-wrap-s+      #x2802)
(defconstant +texture-wrap-t+      #x2803)
(defconstant +texture-min-filter+  #x2801)
(defconstant +texture-mag-filter+  #x2800)
(defconstant +nearest+             #x2600)
(defconstant +linear+              #x2601)
(defconstant +clamp-to-edge+       #x812F)
(defconstant +texture0+            #x84C0)
(defconstant +vertex-shader+       #x8B31)
(defconstant +fragment-shader+     #x8B30)
(defconstant +compile-status+      #x8B81)
